// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcrWTDPSBIEoQygO4T5oW2zPBPO0JKnqk',
    appId: '1:910735088912:web:b30fd3e00c0b00f2f75995',
    messagingSenderId: '910735088912',
    projectId: 'endless-precept-299112',
    authDomain: 'endless-precept-299112.firebaseapp.com',
    storageBucket: 'endless-precept-299112.appspot.com',
    measurementId: 'G-R2255WKT7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMujZv0bv5PDnsuEKLwoTWfkR4bB0oq4Q',
    appId: '1:910735088912:android:454e1e077ff8d908f75995',
    messagingSenderId: '910735088912',
    projectId: 'endless-precept-299112',
    storageBucket: 'endless-precept-299112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDCH8oucRDObW3D_p-QUD_i8a5tC5ChKI',
    appId: '1:910735088912:ios:11a54ad2cb7591fdf75995',
    messagingSenderId: '910735088912',
    projectId: 'endless-precept-299112',
    storageBucket: 'endless-precept-299112.appspot.com',
    iosClientId: '910735088912-f87tj894qki664krkdrr9a0b6khg9tes.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );
}
